### ISSUE TITLE
Kaa alphabet update

### ISSUE THREAD

**Issue by sharapat** [apertium/apertium-uzb-kaa#3]
Now in karakalpak language spelling of these letters o', u', g', a', n' are changed to ó, ú, ǵ, á and ń. Should I change these too? There is karakalpak language book for 10 class pupils [http://n.ziyouz.com/books/qaraqalpaq_kitapxanasi/sabaqliqlar/10-klass/Qaraqalpaq%20tili.%2010-klass%20(2017).pdf](url)

**Comment by jonorthwash** [comment]
Should be moved to https://github.com/apertium/apertium-kaa/issues

**Comment by jonorthwash** [comment]
Now at https://github.com/apertium/apertium-kaa/issues/2
